import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Authenticated Extension Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Extensions
        </h1>

        <p className={styles.description}>
          This is an example app that can be embedded into <a href="https://www.joinportal.com">Portal</a> as an authenticated extension. See the client information below.
        </p>

        <div className={styles.grid}>
        </div>
      </main>
    </div>
  )
}

export default Home
